version: "3"

services:
  sandbox:
    container_name: sandbox
    build:
      context: .
      target: basic_dbg
    volumes:
      - ./drive:/app/drive
      - ./config:/app/.config
      - ./tools:/tools:ro # Read-only, just in case

  sandbox-full:
    container_name: sandbox-full
    build:
      context: .
      target: full_dbg
    volumes:
      - ./drive:/app/drive
      - ./config:/app/.config
      - ./tools:/tools:ro # Read-only, just in case

