version: "3"

services:
  sandbox:
    container_name: sandbox
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./drive:/app/drive
      - ./config/.gdbinit:/root/.gdbinit
      - ./config/.bashrc:/root/.bashrc

