version: "3"

services:
  sandbox:
    privileged: true
    container_name: sandbox
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./drive:/app/drive
      - ./config:/app/.config

