version: "3"

services:
  sandbox:
    container_name: sandbox
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./drive:/app/drive
      - ./config:/app/.config
      - ./tools:/tools:ro # Read-only, just in case

